// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestingMonitor.Infrastructure.Persistence;

#nullable disable

namespace TestingMonitor.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260224195048_Final")]
    partial class Final
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestingMonitor.Domain.Entities.Compiler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CommandName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasDockerLocally")
                        .HasColumnType("boolean");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Version")
                        .IsUnique();

                    b.ToTable("Compilers");
                });

            modelBuilder.Entity("TestingMonitor.Domain.Entities.CompilerTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CompilerId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateOfCompletion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TestGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompilerId");

                    b.HasIndex("TestGroupId");

                    b.HasIndex("TestId");

                    b.ToTable("CompilerTasks");
                });

            modelBuilder.Entity("TestingMonitor.Domain.Entities.HeaderFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("HeaderFiles");
                });

            modelBuilder.Entity("TestingMonitor.Domain.Entities.Test", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TestGroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TestGroupId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("TestingMonitor.Domain.Entities.TestExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DurationInSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<Guid>("ExecutionTaskId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("TestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionTaskId");

                    b.HasIndex("TestId");

                    b.ToTable("TestExecutions");
                });

            modelBuilder.Entity("TestingMonitor.Domain.Entities.TestGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentGroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentGroupId");

                    b.ToTable("TestGroups");
                });

            modelBuilder.Entity("TestingMonitor.Domain.Entities.TestGroupToHeaderFile", b =>
                {
                    b.Property<Guid>("HeaderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TestGroupId")
                        .HasColumnType("uuid");

                    b.HasKey("HeaderId", "TestGroupId");

                    b.HasIndex("TestGroupId");

                    b.ToTable("TestGroupToHeaderFile");
                });

            modelBuilder.Entity("TestingMonitor.Domain.Entities.TestToHeaderFile", b =>
                {
                    b.Property<Guid>("HeaderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid");

                    b.HasKey("HeaderId", "TestId");

                    b.HasIndex("TestId");

                    b.ToTable("TestToHeaderFiles");
                });

            modelBuilder.Entity("TestingMonitor.Domain.Entities.CompilerTask", b =>
                {
                    b.HasOne("TestingMonitor.Domain.Entities.Compiler", "Compiler")
                        .WithMany()
                        .HasForeignKey("CompilerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestingMonitor.Domain.Entities.TestGroup", "TestGroup")
                        .WithMany()
                        .HasForeignKey("TestGroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TestingMonitor.Domain.Entities.Test", "Test")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Compiler");

                    b.Navigation("Test");

                    b.Navigation("TestGroup");
                });

            modelBuilder.Entity("TestingMonitor.Domain.Entities.Test", b =>
                {
                    b.HasOne("TestingMonitor.Domain.Entities.TestGroup", "TestGroup")
                        .WithMany("Tests")
                        .HasForeignKey("TestGroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("TestGroup");
                });

            modelBuilder.Entity("TestingMonitor.Domain.Entities.TestExecution", b =>
                {
                    b.HasOne("TestingMonitor.Domain.Entities.CompilerTask", "ExecutionTask")
                        .WithMany("TestsExecuted")
                        .HasForeignKey("ExecutionTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestingMonitor.Domain.Entities.Test", "Test")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ExecutionTask");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("TestingMonitor.Domain.Entities.TestGroup", b =>
                {
                    b.HasOne("TestingMonitor.Domain.Entities.TestGroup", "ParentGroup")
                        .WithMany("SubGroups")
                        .HasForeignKey("ParentGroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ParentGroup");
                });

            modelBuilder.Entity("TestingMonitor.Domain.Entities.TestGroupToHeaderFile", b =>
                {
                    b.HasOne("TestingMonitor.Domain.Entities.HeaderFile", "HeaderFile")
                        .WithMany("TestGroups")
                        .HasForeignKey("HeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestingMonitor.Domain.Entities.TestGroup", "TestGroup")
                        .WithMany("HeaderFiles")
                        .HasForeignKey("TestGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HeaderFile");

                    b.Navigation("TestGroup");
                });

            modelBuilder.Entity("TestingMonitor.Domain.Entities.TestToHeaderFile", b =>
                {
                    b.HasOne("TestingMonitor.Domain.Entities.HeaderFile", "HeaderFile")
                        .WithMany("Tests")
                        .HasForeignKey("HeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestingMonitor.Domain.Entities.Test", "Test")
                        .WithMany("HeaderFiles")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HeaderFile");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("TestingMonitor.Domain.Entities.CompilerTask", b =>
                {
                    b.Navigation("TestsExecuted");
                });

            modelBuilder.Entity("TestingMonitor.Domain.Entities.HeaderFile", b =>
                {
                    b.Navigation("TestGroups");

                    b.Navigation("Tests");
                });

            modelBuilder.Entity("TestingMonitor.Domain.Entities.Test", b =>
                {
                    b.Navigation("HeaderFiles");
                });

            modelBuilder.Entity("TestingMonitor.Domain.Entities.TestGroup", b =>
                {
                    b.Navigation("HeaderFiles");

                    b.Navigation("SubGroups");

                    b.Navigation("Tests");
                });
#pragma warning restore 612, 618
        }
    }
}
